services:
  shadowvpn2:
    build:
      context: .
      dockerfile: ShadowVPN2/Dockerfile
      target: dev
    container_name: shadowvpn2
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/src:rw
      - ${USERPROFILE}/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5172:8080"
      - "8888:8888"
      - "4443:4443/udp"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - SHADOWVPN_DATA_DIR=/data
    stdin_open: true
    tty: true
